'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowRight, Check, ChevronDown, Sparkles, Stethoscope } from 'lucide-react'
import { ProcessingLoader } from './processing-loader'
import { CtaButton } from './cta-button'

const PASO2_STEPS = ['Analizando tu perfil de equilibrio', 'Seleccionando tu oferta personalizada', 'Reservando tu acceso exclusivo']
const pillars = [
  ['01', 'Evaluación inicial inteligente', 'La IA mapea dónde sientes los síntomas, cuándo comenzaron, su intensidad y cómo afectan tu marcha para crear un perfil único.'],
  ['02', 'Mapa + checklist diario de tus pies', 'Registra dolor, ardor, hormigueo, entumecimiento, sueño y equilibrio en una sola pantalla. Convierte sensaciones en datos reales de tu evolución.'],
  ['03', 'NeuroAssist 24h', 'A las 3 de la mañana, un botón te orienta sobre qué hacer ahora, sin pánico, búsquedas interminables ni esperar al día siguiente.'],
  ['04', 'Detector de señales de alerta', 'Si detecta una herida abierta, enrojecimiento, hinchazón, pérdida repentina de sensibilidad o debilidad nueva, te indica cuándo buscar evaluación médica.'],
  ['05', 'Análisis visual de tus pies con IA', 'Envía una foto para reconocer alteraciones visibles. No diagnostica: te ayuda a identificar cuándo algo merece atención profesional.'],
]
const bonuses = ['Guía Familiar: Cómo Hablar de tu Neuropatía sin Perder tu Independencia', 'Guía de Intimidad y Conexión Sexual', 'Plan Financiero de tu Cuidado', 'Guía Anti-Constreñimiento: El Cuidado Estético de tus Pies', 'El Miedo Silencioso a la Demencia: Guía para Reconocer las Señales y Cómo Prevenirla', '7 Medicamentos que Pueden Afectar Mucho tus Nervios']
const faqs = [
  ['¿Puedo comprarlo después?', 'Esta condición especial está disponible únicamente en esta página. Si cierras esta página, esta oferta no volverá a aparecer.'],
  ['¿Por qué necesito esto si ya tengo los dos protocolos?', 'Porque cumplen funciones diferentes. Un protocolo trabaja tus molestias, otro trabaja movilidad y equilibrio, y la Dieta Japonesa organiza tus hábitos. El Médico Virtual añade un punto de apoyo digital para acompañar tu recorrido.'],
  ['¿Por qué cuesta solamente US$97 con tantos bonos y funcionalidades?', 'Es una condición especial creada como complemento para las personas que ya adquirieron el Método de la Dieta Japonesa.'],
  ['¿Necesito saber usar tecnología?', 'No. Solo necesitas acceder desde tu dispositivo y seguir indicaciones claras, sin conocimientos técnicos avanzados.'],
  ['¿Es difícil utilizarlo?', 'No. Todo está organizado de forma práctica para consultar información, resolver dudas y utilizar las herramientas cuando las necesites.'],
  ['¿Y si no es adecuado para mí?', 'Tienes una garantía de satisfacción de 7 días. Puedes revisar el material y solicitar el reembolso inmediato si no es adecuado para ti.'],
]

function Section({ children, className = '', id }: { children: React.ReactNode; className?: string; id?: string }) {
  return <section id={id} className={`mx-auto w-full max-w-2xl px-5 py-16 sm:py-24 ${className}`}>{children}</section>
}

function PrimaryCta({ children, scrollTo = 'oferta' }: { children: React.ReactNode; scrollTo?: string }) {
  return <CtaButton scrollTo={scrollTo} className="min-h-14 w-full rounded-2xl px-5 text-sm font-extrabold uppercase leading-tight shadow-[0_14px_35px_-12px_var(--primary)] sm:min-h-16 sm:text-base">{children}</CtaButton>
}

export function OtoExperience() {
  const [ready, setReady] = useState(false)
  const [ready2, setReady2] = useState(false)
  const revealed = ready && ready2
  useEffect(() => { if (revealed) window.scrollTo({ top: 0, behavior: 'auto' }) }, [revealed])

  return <>
    {!ready && <ProcessingLoader onDone={() => setReady(true)} />}
    {ready && !ready2 && <ProcessingLoader onDone={() => setReady2(true)} badge="Paso 2 de 3" title="Preparando tu oferta" subtitle="No cierres esta página mientras personalizamos tu oferta." steps={PASO2_STEPS} duration={15000} />}
    <main className={`bg-background text-foreground transition-opacity duration-700 ${revealed ? 'opacity-100' : 'pointer-events-none opacity-0'}`} aria-hidden={!revealed}>
      <div id="pagina">
        <section className="relative overflow-hidden border-b border-primary/25 px-5 pb-16 pt-10 text-center sm:pt-20">
          <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_top,color-mix(in_oklch,var(--primary)_25%,transparent),transparent_65%)]" />
          <div className="mx-auto max-w-2xl">
            <span className="inline-flex items-center gap-2 rounded-full border border-primary/40 bg-primary/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.16em] text-primary"><Stethoscope className="size-3.5" /> Tu nuevo punto de apoyo</span>
            <h1 className="mt-6 text-balance font-display text-3xl font-extrabold uppercase leading-[1.04] tracking-tight sm:text-5xl">Tu Médico Virtual <span className="text-primary">24H</span>: resuelve tu duda urgente de neuropatía al instante</h1>
            <p className="mx-auto mt-5 max-w-xl text-pretty text-sm leading-6 text-muted-foreground sm:text-base">Herramienta de última generación que te conecta al instante con tu Médico Virtual de IA especializado en neuropatía, disponible 24h — para cuando tienes una duda urgente y no puedes esperar días por una cita.</p>
            <img src="/images/medical-ai-mockup.png" alt="Tu Médico Virtual 24H en un teléfono móvil" className="mx-auto mt-9 w-full max-w-[440px] rounded-2xl border border-primary/25 shadow-[0_0_80px_-20px_var(--primary)]" />
            <PrimaryCta>Quiero mi Médico Virtual 24H — US$97</PrimaryCta>
          </div>
        </section>

        <Section className="text-center"><Sparkles className="mx-auto size-7 text-primary" /><p className="mt-4 text-xs font-bold uppercase tracking-[0.18em] text-primary">¡Felicidades!</p><h2 className="mt-3 text-balance font-display text-2xl font-extrabold uppercase sm:text-4xl">Acabas de garantizar tu acceso al Método de la Dieta Japonesa de 14 Días</h2><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-muted-foreground">Ahora ya cuentas con una base para trabajar alimentación, hábitos diarios, una rutina completa y la observación consciente de tus pies.</p><div className="mx-auto mt-8 max-w-xl rounded-2xl border border-primary/20 bg-card p-5 text-left"><p className="font-display text-sm font-extrabold uppercase text-primary">Esto no es otro ebook. Es un punto central para organizar tu proceso.</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Puedes buscar en Google, abrir decenas de vídeos y preguntar en foros. Pero ninguna de esas opciones responde de forma organizada a esa duda específica que es solo tuya.</p></div></Section>

        <Section className="border-y border-border/60"><p className="text-center text-xs font-bold uppercase tracking-[0.18em] text-primary">Zona 2 · Creación del problema</p><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">La diferencia entre tener información y tener un punto de apoyo</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-5"><h3 className="font-display font-extrabold uppercase text-muted-foreground">Tener varios protocolos</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">Lees contenido, recuerdas recomendaciones, abres PDFs, preguntas a familiares y buscas entre decenas de páginas. Al final, pierdes tiempo intentando resolverlo todo por tu cuenta.</p></div><div className="rounded-2xl border border-primary/50 bg-primary/10 p-5 shadow-[0_0_40px_-18px_var(--primary)]"><h3 className="font-display font-extrabold uppercase text-primary">Tener un Médico Virtual 24H</h3><p className="mt-4 text-sm leading-6">Orientación clara durante tu recorrido, sin esperar días, sin depender de tu memoria y sin buscar entre páginas en Internet.</p></div></div></Section>

        <Section><p className="text-center text-xs font-bold uppercase tracking-[0.18em] text-primary">Zona 3 · Mecanismo único</p><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">El sistema médico virtual inteligente</h2><p className="mx-auto mt-4 max-w-xl text-center text-sm leading-6 text-muted-foreground">No es una inteligencia artificial genérica. Es un sistema tecnológico organizado en cinco capas para que siempre tengas un centro de orientación.</p><div className="mt-9 space-y-3">{pillars.map(([number, title, description]) => <article key={number} className="rounded-2xl border border-border bg-card p-5 transition-colors hover:border-primary/50"><div className="flex items-start gap-4"><span className="font-mono text-sm font-bold text-primary">{number}</span><div><h3 className="font-display text-sm font-extrabold uppercase">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div></div></article>)}</div></Section>

        <Section className="border-y border-border/60"><h2 className="text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">Punto de partida → Punto de apoyo → Eslabón de continuidad</h2><div className="mt-8 space-y-4"><div className="rounded-2xl border border-primary/30 bg-primary/10 p-5"><p className="font-display font-extrabold uppercase text-primary">Fase 1 · Punto de partida</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Personalización: el mapeo preciso de dónde te encuentras antes de trazar el camino.</p></div><div className="flex justify-center text-primary"><ArrowDown /></div><div className="rounded-2xl border border-primary/30 bg-primary/10 p-5"><p className="font-display font-extrabold uppercase text-primary">Fase 2 · Punto de apoyo</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Médico Virtual: la orientación adecuada justo en el momento en que surge una duda.</p></div><div className="flex justify-center text-primary"><ArrowDown /></div><div className="rounded-2xl border border-primary/30 bg-primary/10 p-5"><p className="font-display font-extrabold uppercase text-primary">Fase 3 · Eslabón de continuidad</p><p className="mt-2 text-sm leading-6 text-muted-foreground">El hilo conductor que conecta cada etapa de tu proceso sin dejar que te detengas a mitad del camino.</p></div></div></Section>

        <Section><p className="text-center text-xs font-bold uppercase tracking-[0.18em] text-primary">Zona 4 · Prueba social</p><h2 className="mt-3 text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">Personas que dejaron de sentirse solas</h2><div className="mt-8 space-y-4">{[['Miguel, 68 años · Santiago', 'Me quedaba perdido cuando ocurría algo nuevo. Ahora le pregunto al Médico Virtual y recibo orientación en ese mismo momento.'], ['Carlos, 70 años · Medellín', 'Me despertaba con miedo todas las noches. Ahora consulto si es normal o si debo preocuparme. Hoy puedo dormir tranquilo.'], ['Patricia, 58 años · Quito', 'Con el Médico Virtual respondiendo mis dudas al instante, gané mucha confianza y salgo de casa tranquila.']].map(([name, quote]) => <blockquote key={name} className="rounded-2xl border border-border bg-card p-5"><p className="font-display text-sm font-bold text-primary">{name}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">“{quote}”</p><p className="mt-3 tracking-[0.2em] text-primary">★★★★★</p></blockquote>)}</div></Section>

        <Section className="border-y border-border/60"><p className="text-center text-xs font-bold uppercase tracking-[0.18em] text-primary">Zona 5 · Acceso de acompañamiento limitado</p><div className="mt-5 rounded-2xl border border-warning/40 bg-warning/10 p-5 text-center"><p className="font-display text-lg font-extrabold uppercase">Esta condición especial está disponible únicamente en esta página.</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Si sales ahora, no podemos garantizar el mismo precio, la misma disponibilidad ni una nueva incorporación inmediata.</p></div></Section>

        <Section><p className="text-center text-xs font-bold uppercase tracking-[0.18em] text-primary">Zona 6 · Ancoragem e preço</p><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">¿Cuánto vale tener un Médico Virtual que te entiende de por vida?</h2><div className="mt-8 grid gap-3">{['Evaluación Inicial Inteligente', 'Mapa + Checklist Diario', 'NeuroAssist 24h', 'Detector de Señales de Alerta', 'Análisis Visual con IA'].map((item) => <div key={item} className="flex items-start gap-3 rounded-xl border border-border bg-card p-4 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-primary" /><span className="font-semibold">{item}</span></div>)}</div><div className="mx-auto mt-9 max-w-md rounded-3xl border border-primary/40 bg-card p-6 text-center shadow-[0_0_45px_-20px_var(--primary)]"><p className="text-sm text-muted-foreground line-through">Valor total estimado · US$1.497</p><p className="mt-2 text-sm text-muted-foreground line-through">Precio normal · US$997</p><p className="mt-2 text-sm text-muted-foreground line-through">Precio de incorporación · US$697</p><p className="mt-6 font-display text-xs font-bold uppercase tracking-[0.2em] text-primary">Hoy después de tu compra</p><p className="mt-1 font-display text-6xl font-extrabold">US$97</p><p className="mt-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">Pago único · Acceso de por vida</p><PrimaryCta>Quiero mi Médico Virtual de por vida — US$97</PrimaryCta></div></Section>

        <Section><h2 className="text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">6 bonos exclusivos incluidos</h2><div className="mt-8 grid gap-3">{bonuses.map((bonus, index) => <div key={bonus} className="flex gap-3 rounded-xl border border-border bg-card p-4 text-sm leading-6"><span className="font-mono font-bold text-primary">0{index + 1}</span><span><strong className="text-foreground">Bono #{index + 1} — </strong>{bonus}</span></div>)}</div><p className="mt-6 text-center font-display text-lg font-extrabold text-primary">Valor total de los bonos: US$142</p></Section>

        <Section><div className="rounded-3xl border-2 border-warning/40 bg-card p-6 text-center shadow-[0_0_50px_-25px_var(--warning)] sm:p-10"><img src="/images/garantia-7-dias.png" alt="Sello dorado de garantía de 7 días" className="mx-auto size-48 object-contain sm:size-60" /><p className="mt-3 text-xs font-bold uppercase tracking-[0.2em] text-warning">Zona 7 · Eliminación de riesgo</p><h2 className="mt-3 text-balance font-display text-2xl font-extrabold uppercase sm:text-4xl">Garantía de satisfacción de 7 días</h2><p className="mx-auto mt-5 max-w-lg text-sm leading-6 text-muted-foreground">Si por cualquier razón no estás completamente satisfecho con tu Médico Virtual, recibirás un reembolso del 100% sin preguntas. Tú te quedas con todo el acceso. Cero costo, cero complicaciones.</p><div className="mt-6 grid gap-2 text-left text-sm"><p className="flex gap-2"><Check className="size-4 shrink-0 text-warning" /> Funciona o no pagas nada.</p><p className="flex gap-2"><Check className="size-4 shrink-0 text-warning" /> Tú te quedas con todo el contenido.</p><p className="flex gap-2"><Check className="size-4 shrink-0 text-warning" /> El riesgo es 100% nuestro.</p></div></div></Section>

        <Section><p className="text-center text-xs font-bold uppercase tracking-[0.18em] text-primary">Zona 8 · Cierre emocional</p><h2 className="mt-3 text-balance text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">La pieza que faltaba en tu proceso</h2><div className="mt-7 space-y-4 text-sm leading-6 text-muted-foreground"><p>¿Quién está contigo a las 3 de la mañana cuando aparece una duda? ¿Quién te dice si estás en el camino correcto o si algo es grave? ¿Quién te quita el miedo de estar solo en esto?</p><p className="font-display font-extrabold uppercase text-primary">Tu Médico Virtual 24H es la pieza que faltaba.</p><p>No es reemplazar lo que ya tienes. Es tener a alguien observando tu evolución específica todos los días. Es la diferencia entre esperar mejorar y saber que estás mejorando.</p></div><PrimaryCta>Quiero mi Médico Virtual 24H — US$97</PrimaryCta></Section>

        <Section><p className="text-center text-xs font-bold uppercase tracking-[0.18em] text-primary">Zona 9 · Objeciones</p><h2 className="mt-3 text-center font-display text-2xl font-extrabold uppercase sm:text-4xl">Preguntas frecuentes</h2><div className="mt-8 space-y-3">{faqs.map(([question, answer]) => <details key={question} className="group overflow-hidden rounded-2xl border border-border bg-card"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-5 py-5 font-display text-sm font-bold uppercase leading-5"><span>{question}</span><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary transition-transform group-open:rotate-180"><ChevronDown className="size-4" /></span></summary><p className="border-t border-border px-5 pb-5 pt-4 text-sm leading-6 text-muted-foreground">{answer}</p></details>)}</div></Section>

        <Section id="oferta" className="relative overflow-hidden bg-primary px-5 text-center text-primary-foreground"><AlertTriangle className="mx-auto size-8" /><p className="mt-4 text-xs font-bold uppercase tracking-[0.18em] opacity-80">Zona 10 · Cierre final</p><h2 className="mt-3 text-balance font-display text-2xl font-extrabold uppercase sm:text-4xl">Ahora tienes dos opciones</h2><div className="mt-7 grid gap-3 text-left sm:grid-cols-2"><div className="rounded-2xl border border-primary-foreground/20 bg-primary-foreground/10 p-5"><p className="font-display font-extrabold uppercase">Opción 1</p><p className="mt-3 text-sm leading-6 opacity-85">Cerrar esta página, quedarte únicamente con los protocolos y buscar entre varios materiales cada vez que surja una duda urgente.</p></div><div className="rounded-2xl bg-background p-5 text-foreground"><p className="font-display font-extrabold uppercase text-primary">Opción 2</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Recibir tu Médico Virtual 24H, consultar tus síntomas, registrar cambios y descubrir cuándo necesitas acudir a un profesional.</p></div></div><div className="mx-auto mt-8 max-w-md rounded-3xl bg-background p-6 text-left text-foreground"><p className="font-display text-xl font-extrabold uppercase">Tu Médico Virtual 24H</p><p className="mt-3 text-sm leading-6 text-muted-foreground">No otro protocolo. No otro ebook. Un punto de apoyo digital para que nunca te quedes sin saber qué hacer.</p><div className="mt-5 flex items-end justify-between border-t border-border pt-5"><span className="text-xs font-bold uppercase text-muted-foreground">Pago único</span><span className="font-display text-4xl font-extrabold text-primary">US$97</span></div><PrimaryCta scrollTo="pagina">Añadir ahora — US$97 <ArrowRight className="ml-2 inline size-4" /></PrimaryCta></div><p className="mx-auto mt-8 max-w-lg text-xs leading-5 opacity-80">Aviso importante: este programa tiene finalidad educativa y organizativa. El Médico Virtual no sustituye evaluación, diagnóstico, tratamiento, prescripción ni seguimiento de un médico. Ante síntomas graves, busca atención médica inmediata.</p></Section>
      </div>
      <footer className="bg-background px-5 py-10 text-center text-xs text-muted-foreground"><p>Pago seguro · Pago único · Garantía de satisfacción</p><p className="mt-3">© 2026 — Todos los derechos reservados.</p><p className="mx-auto mt-4 max-w-xl leading-5">Política de Privacidad · Términos y Condiciones · Política de Reembolso</p></footer>
    </main>
  </>
}
